# Generated by Django 5.2.15 on 2026-07-07 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_type', models.CharField(choices=[('kpp', 'Kwalifikowana Pierwsza Pomoc'), ('recert', 'Recertyfikacja')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=300)),
                ('max_participants', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pesel', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(blank=True, max_length=20)),
                ('photo_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
