# Generated by Django 5.2.15 on 2026-07-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_location_course_academic_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
